"""fd

Revision ID: 18d3a07cb87a
Revises: 3cb0de38aa04
Create Date: 2022-10-13 14:56:15.766963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18d3a07cb87a'
down_revision = '3cb0de38aa04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vacancy_ibfk_1', 'vacancy', type_='foreignkey')
    op.drop_column('vacancy', 'creator_id')
    op.drop_column('vacancy', 'long_description')
    op.drop_column('vacancy', 'short_description')
    op.drop_column('vacancy', 'rubric_id')
    op.drop_column('vacancy', 'price')
    op.drop_column('vacancy', 'creation_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('creation_date', sa.DATE(), nullable=True))
    op.add_column('vacancy', sa.Column('price', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    op.add_column('vacancy', sa.Column('rubric_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vacancy', sa.Column('short_description', mysql.VARCHAR(length=600), nullable=False))
    op.add_column('vacancy', sa.Column('long_description', mysql.TEXT(), nullable=False))
    op.add_column('vacancy', sa.Column('creator_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vacancy_ibfk_1', 'vacancy', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###
