"""fdsgfd

Revision ID: 1d897ca9f468
Revises: f5df2decbbae
Create Date: 2022-10-05 14:07:31.390845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d897ca9f468'
down_revision = 'f5df2decbbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_experience', sa.Column('link', sa.String(length=420), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_experience', 'link')
    # ### end Alembic commands ###
