"""gender

Revision ID: 42f57a1d9595
Revises: 79f12d8da2d4
Create Date: 2022-10-11 12:31:10.714688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f57a1d9595'
down_revision = '79f12d8da2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'gender', ['gender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'gender_id')
    # ### end Alembic commands ###
