"""sd

Revision ID: 66b36da5323c
Revises: 1d897ca9f468
Create Date: 2022-10-05 14:41:08.997149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b36da5323c'
down_revision = '1d897ca9f468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_experience', sa.Column('skills', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_experience', 'skills')
    # ### end Alembic commands ###
