"""fds

Revision ID: 820927189fd7
Revises: 18d3a07cb87a
Create Date: 2022-10-13 14:58:28.573731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820927189fd7'
down_revision = '18d3a07cb87a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('short_description', sa.String(length=600), nullable=False))
    op.add_column('vacancy', sa.Column('long_description', sa.Text(), nullable=False))
    op.add_column('vacancy', sa.Column('price', sa.Numeric(), nullable=True))
    op.add_column('vacancy', sa.Column('rubric_id', sa.Integer(), nullable=True))
    op.add_column('vacancy', sa.Column('creation_date', sa.Date(), nullable=True))
    op.add_column('vacancy', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancy', 'rubric', ['rubric_id'], ['id'])
    op.create_foreign_key(None, 'vacancy', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.drop_column('vacancy', 'creator_id')
    op.drop_column('vacancy', 'creation_date')
    op.drop_column('vacancy', 'rubric_id')
    op.drop_column('vacancy', 'price')
    op.drop_column('vacancy', 'long_description')
    op.drop_column('vacancy', 'short_description')
    # ### end Alembic commands ###
