"""fd

Revision ID: a67e00088d69
Revises: 820927189fd7
Create Date: 2022-10-13 15:00:21.597606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a67e00088d69'
down_revision = '820927189fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_category', sa.Column('n', sa.Integer(), nullable=True))
    op.drop_column('vacancy_category', 'category_id')
    op.drop_column('vacancy_category', 'vacancy_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_category', sa.Column('vacancy_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('vacancy_category', sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('vacancy_category', 'n')
    # ### end Alembic commands ###
