"""afsd

Revision ID: a78d9530b4d8
Revises: 24c4c153690c
Create Date: 2022-10-12 23:49:15.663490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a78d9530b4d8'
down_revision = '24c4c153690c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_path', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
