"""VacCat

Revision ID: f82c25444706
Revises: a67e00088d69
Create Date: 2022-10-13 15:00:50.051884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f82c25444706'
down_revision = 'a67e00088d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_category', sa.Column('vacancy_id', sa.Integer(), nullable=True))
    op.add_column('vacancy_category', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancy_category', 'vacancy', ['vacancy_id'], ['id'])
    op.create_foreign_key(None, 'vacancy_category', 'category', ['category_id'], ['id'])
    op.drop_column('vacancy_category', 'n')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_category', sa.Column('n', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vacancy_category', type_='foreignkey')
    op.drop_constraint(None, 'vacancy_category', type_='foreignkey')
    op.drop_column('vacancy_category', 'category_id')
    op.drop_column('vacancy_category', 'vacancy_id')
    # ### end Alembic commands ###
